# Generated by Django 5.2.8 on 2025-11-07 03:00

import django.core.validators
import django.db.models.deletion
import profiles.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("default_latitude", models.FloatField(blank=True, null=True)),
                ("default_longitude", models.FloatField(blank=True, null=True)),
                ("default_altitude_m", models.IntegerField(default=0)),
                (
                    "default_skin_type",
                    models.CharField(
                        choices=[
                            ("I", "Type I"),
                            ("II", "Type II"),
                            ("III", "Type III"),
                            ("IV", "Type IV"),
                            ("V", "Type V"),
                            ("VI", "Type VI"),
                        ],
                        default="III",
                        max_length=3,
                    ),
                ),
                (
                    "preferred_time_windows",
                    models.JSONField(default=profiles.models.default_time_windows),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SunProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "relationship",
                    models.CharField(
                        choices=[
                            ("self", "Self"),
                            ("child", "Child"),
                            ("toddler", "Toddler"),
                            ("partner", "Partner"),
                            ("other", "Other"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "age_group",
                    models.CharField(
                        choices=[
                            ("adult", "Adult"),
                            ("child", "Child"),
                            ("toddler", "Toddler"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "skin_type",
                    models.CharField(
                        choices=[
                            ("I", "Fitzpatrick I"),
                            ("II", "Fitzpatrick II"),
                            ("III", "Fitzpatrick III"),
                            ("IV", "Fitzpatrick IV"),
                            ("V", "Fitzpatrick V"),
                            ("VI", "Fitzpatrick VI"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "preferred_time_windows",
                    models.JSONField(default=profiles.models.default_time_windows),
                ),
                (
                    "clothing_preferences",
                    models.JSONField(
                        default=profiles.models.default_clothing_preferences
                    ),
                ),
                (
                    "sunscreen_spf",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(5),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("hats", models.BooleanField(default=True)),
                ("location_latitude", models.FloatField(blank=True, null=True)),
                ("location_longitude", models.FloatField(blank=True, null=True)),
                ("altitude_m", models.IntegerField(default=0)),
                ("is_primary", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sun_profiles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "unique_together": {("user", "name")},
            },
        ),
    ]
